import { DevOneMark } from '@/components/brand/devone-mark';
import {
  IconAdjustmentsHorizontal,
  IconArrowBackUp,
  IconEye,
  IconFilePlus,
  IconFoldUp,
  IconGitPullRequest,
  IconFileCode,
  IconScribble,
  IconSitemap,
  IconMaximize,
  IconMinimize,
  IconFilter,
  IconFiles,
  IconFolderOpen,
  IconGitBranch,
  IconGitCommit,
  IconGitCompare,
  IconArchive,
  IconBraces,
  IconCopy,
  IconFileImport,
  IconFolderPlus,
  IconHistory,
  IconTerminal2,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconBlockquote,
  IconBold,
  IconBox,
  IconBrandApple,
  IconBrandDebian,
  IconBrandGithub,
  IconBrandRedhat,
  IconBrandWindows,
  IconDownload,
  IconBrandGitlab,
  IconBrandTwitter,
  IconBrightness,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconColumns,
  IconDatabase,
  IconHash,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconItalic,
  IconH1,
  IconKey,
  IconLink,
  IconList,
  IconListNumbers,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlugConnected,
  IconPlugConnectedX,
  IconPlus,
  IconProps,
  IconRefresh,
  IconRosetteDiscountCheck,
  IconSearch,
  IconSelector,
  IconSend,
  IconServer2,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconStrikethrough,
  IconTable,
  IconTrash,
  IconTrendingDown,
  IconTarget,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconCrown,
  IconX,
  IconChevronsUp,
  IconProgress,
  IconCircleDashed,
  IconCalendarX,
  IconCalendarClock,
  IconCircleHalf2,
  IconCircleDotted,
  IconCircleDot,
  IconProgressHelp,
  IconProgressAlert,
  IconProgressCheck,
  IconCircleCheckFilled,
  IconCircleMinus,
  IconCircleDashedCheck
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  gitlab: IconBrandGitlab,
  apple: IconBrandApple,
  windows: IconBrandWindows,
  debian: IconBrandDebian,
  redhat: IconBrandRedhat,
  twitter: IconBrandTwitter,
  logo: DevOneMark as Icon,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  download: IconDownload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  trendingDown: IconTrendingDown,
  target: IconTarget,
  trendingUp: IconTrendingUp,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  strikethrough: IconStrikethrough,
  heading: IconH1,
  quote: IconBlockquote,
  link: IconLink,
  list: IconList,
  listOrdered: IconListNumbers,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,

  // Database
  database: IconDatabase,
  table: IconTable,
  primaryKey: IconKey,
  foreignKey: IconLink,
  index: IconHash,
  columns: IconColumns,
  server: IconServer2,
  connected: IconPlugConnected,
  disconnected: IconPlugConnectedX,
  refresh: IconRefresh,
  run: IconPlayerPlay,
  pause: IconPlayerPause,

  // API client
  copy: IconCopy,
  folder: IconFolder,
  folderPlus: IconFolderPlus,
  history: IconHistory,
  import: IconFileImport,
  terminal: IconTerminal2,
  braces: IconBraces,

  // Git workbench
  fileCode: IconFileCode,
  files: IconFiles,
  folderOpen: IconFolderOpen,
  gitBranch: IconGitBranch,
  gitCommit: IconGitCommit,
  gitCompare: IconGitCompare,
  archive: IconArchive,
  gitPullRequest: IconGitPullRequest,
  filePlus: IconFilePlus,
  collapseAll: IconFoldUp,
  discard: IconArrowBackUp,
  eye: IconEye,
  filter: IconFilter,
  drawing: IconScribble,
  diagram: IconSitemap,
  maximize: IconMaximize,
  minimize: IconMinimize,

  // Board
  priorityUrgent: IconAlertCircle,
  priorityHigh: IconChevronsUp,
  priorityMedium: IconChevronUp,
  priorityLow: IconChevronDown,
  priorityNone: IconMinus,
  statusTodo: IconCircle,
  statusProgress: IconProgress,
  statusBacklog: IconCircleDashed,
  statusReview: IconCircleHalf2,
  statusDone: IconCircleCheck,
  statusTriage: IconCircleDotted,
  statusStarted: IconCircleDot,
  statusTesting: IconProgressHelp,
  statusBlocked: IconProgressAlert,
  statusReady: IconProgressCheck,
  statusDoneFilled: IconCircleCheckFilled,
  statusVerified: IconCircleDashedCheck,
  statusCancelled: IconCircleX,
  statusPaused: IconCircleMinus,
  comment: IconMessage,
  calendarOverdue: IconCalendarX,
  calendarSoon: IconCalendarClock
};
